### ISSUE TITLE
exclude  android:allowBackup="true" from manifest

### ISSUE THREAD

**Issue by fgtmenow** [MostafaNasiri/AndroidFileChooser#10]

**Comment by MostafaNasiri** [comment]
Why?

**Comment by fgtmenow** [comment]
if you add this library as dependency to project, that have allowBackup="false" you will get Minifest merging error.

You dont need this feature into your library. There is no SharedPrefetences.

**Comment by MostafaNasiri** [comment]
Ok I will remove it in the next release. Until then you can add tools:replace="allowBackup" to application tag in your manifest file.
