### ISSUE TITLE
Handling back button when adding fragment in existing FragmentManager

### ISSUE THREAD

**Issue by albert0m** [MostafaNasiri/AndroidFileChooser#11]
I'm using a FragmentManager and I'm opening one fragment after another. The the user choose to open a file, and I add your library inside my existing FragmentManager.

`FragmentTransaction fragmentTransaction = getChildFragmentManager().beginTransaction();
		fragmentTransaction.replace(R.id.fragment, fragment);
		fragmentTransaction.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE);
		fragmentTransaction.commit();`

I don't add it to the backstack, but when I hit back it's still present in the backstack and the previous fragments wiped from the backstack
Do you know why whould this happen? thank you

**Comment by MostafaNasiri** [comment]
Sorry for answering too late. What do you do after the user selects a file or directory? Do you open a new activity?

**Comment by MostafaNasiri** [comment]
Closed for not getting any response.
