### ISSUE TITLE
Bugs with Multiple Selection Feature

### ISSUE THREAD

**Issue by programmeraditya** [MostafaNasiri/AndroidFileChooser#13]
I found multiple bugs with the said feature.

1. Selected files in the list are not highlighted, which makes it very difficult for the user to know which files have been selected.
2. By default, the button for the selection has no text.
3. As I wrote in the previous issue, there's no limit to how many files can be selected. Also, to add to this, there should be a counter showing the total number of files selected out of the limit.

**Comment by MostafaNasiri** [comment]
1. Well they are indicated by checkbox but we can also add some kind of selected effect to selected items. I see what I can do.
2. You can easily set your desired text on the button.
3. I'm working on it.
