### ISSUE TITLE
Directory mode error

### ISSUE THREAD

**Issue by cdbbnnyCode** [MostafaNasiri/AndroidFileChooser#14]
If the file chooser type is set to `FileChooserDialog.ChooserType.DIRECTORY_CHOOSER`, then
calling `setMultipleFileSelectionEnabled(boolean)` will *always* throw an IllegalArgumentException, even if the program is setting it to false.

**Comment by MostafaNasiri** [comment]
Methods that are specific to FILE_CHOOSER always throw IllegalStateException when called on a DIRECTORY_CHOOSER.

**Comment by cdbbnnyCode** [comment]
Ah, I see.
