### ISSUE TITLE
Question: Is it possible to pickup folder as a path?

### ISSUE THREAD

**Issue by isabsent** [MostafaNasiri/AndroidFileChooser#16]
I need to select and pickup the selected folder path. Is it possible with your library?

**Comment by MostafaNasiri** [comment]
Yes. You can use this library as a directory chooser.

**Comment by isabsent** [comment]
It is `minSdkVersion 16` in the library `build.gradle`. Which feature demands this SDK? Is it possible to lower it to SDK 14? 

Other question is about picking file or folder on a **removable** SD-card or USB OTG drive. Is it possible?

**Comment by MostafaNasiri** [comment]
You can clone this repo and see if it has any problem with sdk version 14 and create a pull request if it worked correctly.
It is possible to pick files and folders on removable sd card but I'm not sure about the USB OTG drive.

**Comment by isabsent** [comment]
Thanks! I will try.
